services:
  jenkins:
    image: jenkins/jenkins:lts-jdk21
    container_name: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes: 
      - jenkins_homes:/var/jenkins_home
    restart: unless-stopped
volumes:
  jenkins_homes:

